import type { ScanQuestion, ScanSection } from '@/types/scan';

// ─── SECTION 1 — LA RUOTA DELLA VITA (D1–D24) ────────────────────────────────

const SECTION_1_QUESTIONS: ScanQuestion[] = [
  {
    id: 'D1', n: 1, section: 1,
    text: 'Quanto sei soddisfatto della tua salute e del tuo corpo in questo momento?',
    type: 'SCALA',
  },
  {
    id: 'D2', n: 2, section: 1,
    text: 'Quando si tratta della tua salute, qual è il pattern che si ripete più spesso?',
    type: 'SCELTA',
    options: [
      'Ho una routine solida e la vivo con piacere, non con rigidità',
      'Vado bene per un periodo poi mollo tutto — cicli di disciplina e abbandono',
      'Non mi prendo mai cura di me — metto sempre gli altri o il lavoro prima',
      'Sono perfezionista — o tutto o niente, non esiste una via di mezzo',
      'Faccio fatica a fermarmi e ascoltare i segnali del corpo',
      'Non ho ancora un pattern chiaro — sto ancora capendo il mio rapporto con la salute',
    ],
  },
  {
    id: 'D3', n: 3, section: 1,
    text: 'Con il mio corpo ho un rapporto...',
    type: 'FRASE',
    placeholder: 'Completa la frase con la prima cosa che ti viene',
  },
  {
    id: 'D4', n: 4, section: 1,
    text: 'Quanto sei soddisfatto delle tue relazioni intime e romantiche?',
    type: 'SCALA',
  },
  {
    id: 'D5', n: 5, section: 1,
    text: 'Nelle relazioni profonde, cosa succede di solito quando raggiungi una vera intimità?',
    type: 'SCELTA',
    options: [
      'Mi apro e mi avvicino — l\'intimità mi nutre',
      'Mi avvicino poi inconsapevolmente trovo un motivo per allontanarmi',
      'Mi perdo — do tutto me stesso fino a dimenticare chi sono',
      'Ho paura di non essere abbastanza per l\'altro',
      'Prendo il controllo — è il mio modo di sentirmi sicuro',
      'Mi adatto completamente all\'altro perdendo la mia identità',
      'Non ci sono ancora arrivato — non ho abbastanza dati su di me in questa situazione',
    ],
  },
  {
    id: 'D6', n: 6, section: 1,
    text: 'Cosa ti hanno detto più spesso le persone con cui sei stato in relazione?',
    type: 'MULTI',
    options: [
      '"Sei presente e mi fai sentire visto"',
      '"Sei sempre assente anche quando sei presente"',
      '"Non ti apri mai davvero"',
      '"Fai sempre di testa tua"',
      '"Dai troppo e poi sparisci"',
      '"Non so mai cosa pensi davvero"',
      '"Sei troppo intenso"',
      '"Non ti fidi mai completamente"',
      'Non ho avuto relazioni abbastanza lunghe da ricevere questo tipo di feedback',
    ],
  },
  {
    id: 'D7', n: 7, section: 1,
    text: 'Quanto è soddisfacente la qualità delle tue relazioni familiari oggi?',
    type: 'SCALA',
  },
  {
    id: 'D8', n: 8, section: 1,
    text: 'Nella tua famiglia di origine, il successo e il denaro erano vissuti come...',
    type: 'SCELTA',
    options: [
      'Qualcosa di normale e accessibile — si guadagna e si gestisce con serenità',
      'Qualcosa per "gli altri", non per noi',
      'Una fonte di conflitto o stress costante',
      'L\'unica cosa che contava — il valore di una persona',
      'Qualcosa di cui non si parlava — tabù',
      'Non ho un\'immagine chiara di come venivano vissuti in famiglia',
    ],
  },
  {
    id: 'D9', n: 9, section: 1,
    text: 'C\'è qualcosa che hai realizzato o vuoi realizzare che senti potrebbe creare distanza dalla tua famiglia o dalle tue origini?',
    type: 'ACCORDO',
    subtext: '1 = Per niente | 5 = Molto — sento il peso di questa tensione',
  },
  {
    id: 'D10', n: 10, section: 1,
    text: 'Quanto sei soddisfatto di ciò che hai costruito professionalmente?',
    type: 'SCALA',
  },
  {
    id: 'D11', n: 11, section: 1,
    text: 'Qual è il pattern che si ripete di più nella tua carriera o business?',
    type: 'SCELTA',
    options: [
      'Costruisco con costanza e porto a compimento ciò che inizio',
      'Arrivo vicino a qualcosa di grande poi qualcosa va storto',
      'Ho mille idee ma faccio fatica a portarne una fino in fondo',
      'Faccio tutto da solo perché nessuno lo fa bene come me',
      'Non lancio mai perché non è ancora abbastanza buono',
      'Mi adatto a ciò che vogliono gli altri invece di seguire la mia visione',
      'Sono ancora nelle fasi iniziali — non ho ancora un pattern chiaro',
    ],
  },
  {
    id: 'D12', n: 12, section: 1,
    text: 'Nel mio lavoro, la cosa che mi blocca di più è...',
    type: 'FRASE',
    placeholder: 'Completa la frase con la prima cosa che ti viene',
  },
  {
    id: 'D13', n: 13, section: 1,
    text: 'Quanto sei soddisfatto della tua situazione finanziaria attuale?',
    type: 'SCALA',
  },
  {
    id: 'D14', n: 14, section: 1,
    text: 'Quando pensi ai soldi, qual è la prima emozione che senti?',
    type: 'SCELTA',
    options: [
      'Sicurezza e tranquillità — ho un rapporto sano con il denaro',
      'Ansia e preoccupazione costante',
      'Senso di colpa — come se non meritassi di averne',
      'Eccitazione ma anche paura che finisca',
      'Indifferenza o distacco — i soldi non mi interessano davvero',
      'Vergogna — per quanto ne ho o per quanto non ne ho',
      'Non ho ancora esplorato il mio rapporto emotivo con il denaro',
    ],
  },
  {
    id: 'D15', n: 15, section: 1,
    text: 'Quando guadagni bene, cosa tende a succedere?',
    type: 'SCELTA',
    options: [
      'Risparmio, investo con criterio e godo serenamente di ciò che ho',
      'Trovo modi per spendere o disperdere — torna sempre al punto di partenza',
      'Mi sento in colpa e cerco di dare via o aiutare gli altri',
      'Investo in nuovi progetti — spesso troppi contemporaneamente',
      'Ho paura che possa finire e fatico a goderne',
      'Non ho ancora guadagnato abbastanza a lungo da riconoscere un pattern',
    ],
  },
  {
    id: 'D16', n: 16, section: 1,
    text: 'Quanto stai investendo nella tua crescita personale in modo efficace?',
    type: 'SCALA',
  },
  {
    id: 'D17', n: 17, section: 1,
    text: 'Come descriveresti il tuo approccio alla crescita personale?',
    type: 'SCELTA',
    options: [
      'Ho una pratica integrata — studio, applico, integro con costanza',
      'Leggo e studio molto ma faccio fatica ad applicare e integrare',
      'Salto da un corso all\'altro, da un guru all\'altro cercando la risposta',
      'Mi dedico alla crescita solo quando sono in crisi',
      'Non è ancora una priorità consapevole nella mia vita',
      'Sto ancora capendo cosa significa crescita personale per me',
    ],
  },
  {
    id: 'D18', n: 18, section: 1,
    text: 'Qual è la cosa che sai da anni che dovresti fare per la tua crescita ma continui a rimandare?',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
  {
    id: 'D19', n: 19, section: 1,
    text: 'Quanto spazio dai al gioco, al divertimento, alla creatività nella tua vita?',
    type: 'SCALA',
  },
  {
    id: 'D20', n: 20, section: 1,
    text: 'Quando ti concedi del tempo per te — senza obiettivi, senza produttività — come ti senti?',
    type: 'SCELTA',
    options: [
      'In pace e ricaricato — è nutrimento essenziale per me',
      'In colpa — come se stessi sprecando tempo prezioso',
      'Ansioso — ho bisogno di fare qualcosa di utile',
      'Non riesco a farlo davvero — finisco sempre per lavorare',
      'È così raro che non so come mi sentirei',
      'Non mi è mai capitato abbastanza a lungo da saperlo',
    ],
  },
  {
    id: 'D21', n: 21, section: 1,
    text: 'Hai una forma di espressione creativa nella tua vita?',
    type: 'SCELTA',
    options: [
      'Sì, è parte centrale e nutrente della mia vita',
      'Sì, ma non le do abbastanza spazio — la sopprimo spesso',
      'Avevo una passione creativa che ho abbandonato nel tempo',
      'Non ho ancora trovato la mia forma naturale di espressione',
      'Non ho mai pensato alla creatività come qualcosa che mi riguarda',
    ],
  },
  {
    id: 'D22', n: 22, section: 1,
    text: 'Quanto senti che la tua vita ha uno scopo chiaro e stai contribuendo a qualcosa di più grande?',
    type: 'SCALA',
  },
  {
    id: 'D23', n: 23, section: 1,
    text: 'Quando pensi all\'impatto che vuoi avere nel mondo, cosa senti?',
    type: 'SCELTA',
    options: [
      'Chiarezza e motivazione — so cosa voglio creare e ci sto lavorando',
      'Una visione potente ma frustrazione perché non si realizza abbastanza',
      'Confusione — non so ancora quale sia il mio contributo unico',
      'Grandiosità — ho una missione che pochi comprendono davvero',
      'Senso di colpa — potrei fare molto di più di quello che faccio',
      'Non ho ancora trovato uno scopo che sento davvero mio',
    ],
  },
  {
    id: 'D24', n: 24, section: 1,
    text: 'Il contributo che voglio dare al mondo è...',
    type: 'FRASE',
    placeholder: 'Completa la frase con la prima cosa che ti viene',
  },
];

// ─── SECTION 2 — I PATTERN COMPORTAMENTALI (D25–D59) ─────────────────────────

const SECTION_2_QUESTIONS: ScanQuestion[] = [
  {
    id: 'D25', n: 25, section: 2,
    text: 'Stai per lanciare qualcosa di importante. Cosa succede nei giorni prima?',
    type: 'MULTI',
    options: [
      'Mi sento focalizzato e pronto — l\'eccitazione supera l\'ansia',
      'Trovo mille cose da sistemare prima — non è mai il momento giusto',
      'Rimando perché "non è ancora abbastanza buono"',
      'Mi ammalo o mi stanco improvvisamente',
      'Creo un conflitto con qualcuno di importante per me',
      'Sono iperproduttivo ma su cose secondarie e irrilevanti',
      'Cerco conferme e rassicurazioni in modo compulsivo',
      'Non ho ancora vissuto abbastanza lanci per riconoscere un pattern',
    ],
  },
  {
    id: 'D26', n: 26, section: 2,
    text: 'Qualcuno ti chiede un favore che non hai voglia di fare. Cosa fai?',
    type: 'SCELTA',
    options: [
      'Dico no con chiarezza e senza senso di colpa',
      'Dico sì anche se non voglio — e poi me ne pento',
      'Dico sì e lo faccio con rancore silenzioso',
      'Trovo una scusa per evitare senza dire no direttamente',
      'Dipende totalmente da chi me lo chiede — non ho una linea chiara',
      'Non mi è mai capitato in modo abbastanza diretto da saperlo',
    ],
  },
  {
    id: 'D27', n: 27, section: 2,
    text: 'Hai appena ottenuto un grande risultato. Come reagisci internamente?',
    type: 'SCELTA',
    options: [
      'Gioia piena — lo celebro davvero prima di andare al prossimo obiettivo',
      'Sollievo momentaneo, poi immediatamente al prossimo traguardo',
      '"Era il minimo — potevo e dovevo fare di più"',
      'Ansia — e adesso? Riuscirò a mantenere questo livello?',
      'Senso di irrealtà — non sembra davvero mio, aspetto che finisca',
      'Preoccupazione per cosa cambierà nella mia vita con questo successo',
      'Non ho ancora raggiunto risultati grandi abbastanza da saperlo',
    ],
  },
  {
    id: 'D28', n: 28, section: 2,
    text: 'Stai lavorando in team. Un collaboratore fa qualcosa diversamente da come lo faresti tu. Cosa fai?',
    type: 'SCELTA',
    options: [
      'Lo lascio fare — ci sono molti modi validi per fare bene le cose',
      'Intervengo e mostro come lo farei io',
      'Lo faccio io stesso per essere sicuro del risultato finale',
      'Mi trattengo esternamente ma internamente sono in tensione',
      'Lo critico — a volte lo dico, a volte no',
      'Non ho mai avuto abbastanza collaboratori per saperlo',
    ],
  },
  {
    id: 'D29', n: 29, section: 2,
    text: 'Qualcuno ti fa una critica sul tuo lavoro. Come reagisci?',
    type: 'SCELTA',
    options: [
      'L\'accolgo, valuto se ha senso, la integro se è utile',
      'Mi difendo — spiego perché ho fatto così',
      'Fuori concordo, dentro mi distruggo',
      'La critica mi conferma qualcosa di negativo che penso già di me',
      'Penso che chi critica non capisce davvero la mia visione',
      'Mi blocco completamente per un po\' — perdo lo slancio',
      'Dipende molto dalla persona — non ho una reazione consistente',
    ],
  },
  {
    id: 'D30', n: 30, section: 2,
    text: 'Descrivi una situazione che si è ripetuta almeno 3 volte nella tua vita — contesti diversi, stesso risultato.',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
  {
    id: 'D31', n: 31, section: 2,
    text: 'Quando stai per raggiungere qualcosa di importante per te, cosa succede di solito?',
    type: 'SCELTA',
    options: [
      'Lo raggiungo, lo celebro, e uso lo slancio per andare avanti',
      'Qualcosa va storto proprio quando ero più vicino',
      'Faccio fatica ad arrivare fino in fondo — mi fermo prima',
      'Lo raggiungo ma non mi soddisfa mai abbastanza — voglio subito altro',
      'Mi spaventa quasi quanto non raggiungerlo',
      'Non ho ancora avuto obiettivi abbastanza grandi da riconoscere il pattern',
    ],
  },
  {
    id: 'D32', n: 32, section: 2,
    text: 'Come gestisci i tuoi errori?',
    type: 'SCELTA',
    options: [
      'Li analizzo, estraggo l\'apprendimento e vado avanti con leggerezza',
      'Mi autocritico duramente per un po\' poi riesco a passare oltre',
      'Faccio fatica a perdonarmi — rimangono con me a lungo',
      'Li minimalizzo o li nascondo — anche a me stesso',
      'Li uso come ulteriore conferma che non sono abbastanza',
      'Non ho ancora capito il mio pattern con gli errori',
    ],
  },
  {
    id: 'D33', n: 33, section: 2,
    text: 'Quanto spesso dici sì a cose nuove anche quando hai già troppe cose in corso?',
    type: 'SCALA',
    subtext: '1 = Quasi mai — so gestire i miei confini | 10 = Quasi sempre — faccio fatica a dire no',
  },
  {
    id: 'D34', n: 34, section: 2,
    text: 'Quando sei sotto pressione, qual è il tuo comportamento automatico?',
    type: 'MULTI',
    options: [
      'Resto focalizzato e aumento la qualità del lavoro',
      'Lavoro di più e più duramente anche quando non serve',
      'Mi isolo completamente',
      'Procrastino con attività secondarie o irrilevanti',
      'Mi disconnetto (telefono, TV, cibo, altro)',
      'Divento irritabile o aggressivo con chi mi è vicino',
      'Cerco di controllare ogni dettaglio di ciò che posso',
      'Mi paralizzo — non riesco a fare nulla',
      'Non so ancora come reagisco sotto vera pressione',
    ],
  },
  {
    id: 'D35', n: 35, section: 2,
    text: 'Hai una visione o un sogno che porti dentro da anni ma non hai ancora realizzato. Qual è il motivo principale?',
    type: 'SCELTA',
    options: [
      'Sto lavorando attivamente — ci sono ostacoli reali ma li sto superando',
      'Non è mai il momento giusto — c\'è sempre qualcosa da sistemare prima',
      'Ho paura di fallire e di confermare di non essere abbastanza',
      'Ho paura di avere successo e di cosa cambierebbe nella mia vita',
      'Ho iniziato molte volte ma non sono mai arrivato in fondo',
      'Gli altri non capiscono la mia visione e questo mi blocca',
      'Non ho ancora una visione chiara abbastanza da chiamarla sogno',
    ],
  },
  {
    id: 'D36', n: 36, section: 2,
    text: 'Quando deleghi qualcosa a qualcuno, cosa senti?',
    type: 'SCELTA',
    options: [
      'Sollievo genuino — posso concentrarmi su ciò che conta davvero',
      'Ansia — e se lo fa male o diversamente da come lo farei io?',
      'Lo delego ma poi controllo comunque — non riesco a lasciar andare',
      'Faccio fatica a delegare — preferisco farlo io per sicurezza',
      'Non delego quasi mai — è più veloce farlo io',
      'Non ho ancora avuto abbastanza occasioni di delega per saperlo',
    ],
  },
  {
    id: 'D37', n: 37, section: 2,
    text: 'Come ti comporti quando qualcuno che ami è in difficoltà?',
    type: 'SCELTA',
    options: [
      'Offro presenza e supporto emotivo senza cercare di risolvere per loro',
      'Cerco immediatamente di risolvere il problema — non reggo vederli soffrire',
      'Mi faccio carico emotivamente anche oltre le mie forze',
      'Mi distanzio — non so gestire bene il dolore altrui',
      'Offro consigli anche quando non vengono chiesti',
      'Dipende molto dalla persona e dalla situazione',
    ],
  },
  {
    id: 'D38', n: 38, section: 2,
    text: 'Hai mai abbandonato un progetto, una relazione, o un\'opportunità nel momento in cui stava diventando davvero reale e concreta?',
    type: 'ACCORDO',
    subtext: '1 = Mai — porto a compimento ciò che inizio | 5 = Spesso — è un pattern che riconosco',
  },
  {
    id: 'D39', n: 39, section: 2,
    text: 'Quanto spesso confronti te stesso con gli altri?',
    type: 'SCALA',
    subtext: '1 = Quasi mai — uso il confronto come ispirazione | 10 = Costantemente',
  },
  {
    id: 'D40', n: 40, section: 2,
    text: 'Quando prendi una decisione importante, da cosa sei guidato principalmente?',
    type: 'SCELTA',
    options: [
      'Da una visione chiara e da valori solidi — so perché scelgo',
      'Da cosa pensano o si aspettano gli altri',
      'Da cosa mi fa sentire più sicuro e al riparo dal rischio',
      'Da cosa evita il conflitto o il disagio con persone importanti',
      'Da regole e principi rigidi che non si discutono',
      'Non ho ancora capito bene cosa guida davvero le mie decisioni',
    ],
  },
  {
    id: 'D41', n: 41, section: 2,
    text: 'Descrivi come ti comporti in una situazione di conflitto diretto con qualcuno importante per te.',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
  {
    id: 'D42', n: 42, section: 2,
    text: 'Quanto ti è facile chiedere aiuto quando ne hai bisogno?',
    type: 'SCALA',
    subtext: '1 = Impossibile — preferisco fare da solo | 10 = Facile e naturale',
  },
  {
    id: 'D43', n: 43, section: 2,
    text: 'Hai mai sabotato consapevolmente o inconsapevolmente qualcosa che stava andando bene?',
    type: 'ACCORDO',
    subtext: '1 = Mai — non riconosco questo pattern | 5 = Sì, è qualcosa che noto chiaramente',
  },
  {
    id: 'D44', n: 44, section: 2,
    text: 'Come reagisci quando le persone si aspettano qualcosa da te?',
    type: 'SCELTA',
    options: [
      'Le aspettative mi motivano senza mettermi pressione — le uso come carburante',
      'Mi mettono pressione ma riesco a gestirla senza perdere me stesso',
      'Mi sento intrappolato e voglio fare l\'opposto — per principio',
      'Cerco di soddisfarle anche a mie spese — non riesco a deludere',
      'Mi paralizzano — e se non fossi all\'altezza?',
      'Non ho ancora capito come reagisco alle aspettative altrui',
    ],
  },
  {
    id: 'D45', n: 45, section: 2,
    text: 'Quanto tempo dedichi mediamente ogni settimana a cose che ami fare senza uno scopo produttivo?',
    type: 'SCELTA',
    options: [
      'Molto — è una priorità che proteggo attivamente',
      'Il giusto — abbastanza da sentirmi nutrito',
      'Qualche ora — meno di quanto vorrei',
      'Quasi nulla — non ho tempo o mi sento in colpa',
      'Non ho ancora capito cosa mi nutre davvero senza scopo produttivo',
    ],
  },
  {
    id: 'D46', n: 46, section: 2,
    text: 'La cosa che mi spaventa di più nel diventare la persona che voglio essere è...',
    type: 'FRASE',
    placeholder: 'Completa la frase con la prima cosa che ti viene',
  },
  {
    id: 'D47', n: 47, section: 2,
    text: 'Quando inizi qualcosa di nuovo, fino a dove arrivi tipicamente?',
    type: 'SCELTA',
    options: [
      'Lo porto sempre a termine — l\'impegno è un valore che vivo davvero',
      'Arrivo all\'80% poi perdo interesse o slancio',
      'Spesso non supero la fase iniziale entusiasmante',
      'Finisco ciò che mi appassiona davvero — il resto lo abbandono',
      'Non ho ancora un pattern chiaro su questo',
    ],
  },
  {
    id: 'D48', n: 48, section: 2,
    text: 'Quanto ti senti libero di essere esattamente te stesso in tutti i contesti della tua vita?',
    type: 'SCALA',
    subtext: '1 = Per niente — cambio molto a seconda del contesto | 10 = Completamente — sono lo stesso ovunque',
  },
  {
    id: 'D49', n: 49, section: 2,
    text: 'Descrivi l\'ultima volta che hai fatto qualcosa che sapevi non fosse nel tuo interesse ma l\'hai fatto comunque. Perché?',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
  {
    id: 'D50', n: 50, section: 2,
    text: 'Quanto spesso ti senti esausto pur non avendo fatto cose fisicamente pesanti?',
    type: 'SCALA',
    subtext: '1 = Quasi mai — la mia energia è stabile | 10 = Costantemente — sempre stanco senza motivo chiaro',
  },
  {
    id: 'D51', n: 51, section: 2,
    text: 'Quando hai un\'idea nuova e grande, qual è la tua reazione tipica?',
    type: 'SCELTA',
    options: [
      'La valuto con calma e discernimento — non tutte le idee meritano esecuzione',
      'Mi entusiasmo immediatamente e voglio iniziare subito',
      'La condivido con tutti cercando conferme e validazione',
      'La tengo per me — gli altri non capirebbero o ruberebbero',
      'Inizia a sembrare meno interessante appena la metto in pratica',
      'Non ho ancora abbastanza idee grandi per riconoscere un pattern',
    ],
  },
  {
    id: 'D52', n: 52, section: 2,
    text: 'Quanto influenzano le opinioni degli altri le tue decisioni importanti?',
    type: 'SCALA',
    subtext: '1 = Quasi nulla — ascolto ma decido da me | 10 = Moltissimo — faccio fatica senza approvazione',
  },
  {
    id: 'D53', n: 53, section: 2,
    text: 'Hai mai raggiunto un obiettivo importante e poi sabotato i risultati nel tempo?',
    type: 'ACCORDO',
    subtext: '1 = Mai — mantengo e consolido i risultati | 5 = Sì — è un pattern che riconosco',
  },
  {
    id: 'D54', n: 54, section: 2,
    text: 'Come descrivi il tuo rapporto con le regole e le strutture?',
    type: 'SCELTA',
    options: [
      'Le uso come strumento — le seguo quando servono, le adatto quando necessario',
      'Le rispetto sempre — danno ordine e sicurezza',
      'Mi danno fastidio — mi sento limitato e controllato',
      'Le creo per gli altri ma fatico a seguirle io stesso',
      'Le uso come scusa per non rischiare — "non si può fare"',
      'Non ho ancora un rapporto chiaro con regole e strutture',
    ],
  },
  {
    id: 'D55', n: 55, section: 2,
    text: 'Quanto spesso ti senti completamente presente e nel flusso in ciò che fai?',
    type: 'SCALA',
    subtext: '1 = Quasi mai — sono spesso altrove | 10 = Spesso — il flusso è naturale nella mia vita',
  },
  {
    id: 'D56', n: 56, section: 2,
    text: 'Se non avessi paura di niente, la prima cosa che farei è...',
    type: 'FRASE',
    placeholder: 'Completa la frase con la prima cosa che ti viene',
  },
  {
    id: 'D57', n: 57, section: 2,
    text: 'Quando qualcosa va male nella tua vita, qual è la tua prima reazione?',
    type: 'SCELTA',
    options: [
      'Analizzo, estraggo l\'apprendimento e vado avanti',
      'Mi autoaccuso — avrei potuto e dovuto fare meglio',
      'Cerco un responsabile esterno — non è colpa mia',
      'Mi chiudo e aspetto che passi da solo',
      'Cerco subito una soluzione senza elaborare cosa è successo',
      'Mi sento confermato in qualcosa di negativo che penso già di me',
      'Le situazioni difficili sono ancora troppo recenti per riconoscere un pattern',
    ],
  },
  {
    id: 'D58', n: 58, section: 2,
    text: 'Quanto spesso fai cose per paura delle conseguenze piuttosto che per genuino desiderio?',
    type: 'SCALA',
    subtext: '1 = Quasi mai — agisco da desiderio genuino | 10 = Quasi sempre — la paura guida le mie scelte',
  },
  {
    id: 'D59', n: 59, section: 2,
    text: 'Descrivi come prendi tipicamente le decisioni importanti.',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
];

// ─── SECTION 3 — LE CREDENZE FONDANTI (D60–D84) ──────────────────────────────

const SECTION_3_QUESTIONS: ScanQuestion[] = [
  {
    id: 'D60', n: 60, section: 3,
    text: '"Le persone come me non possono..."',
    type: 'FRASE',
    placeholder: 'Completa con la prima cosa che ti viene, senza filtrare',
  },
  {
    id: 'D61', n: 61, section: 3,
    text: '"Il successo per me significa..."',
    type: 'FRASE',
    placeholder: 'Completa con la prima cosa che ti viene',
  },
  {
    id: 'D62', n: 62, section: 3,
    text: '"I soldi sono..."',
    type: 'FRASE',
    placeholder: 'Completa con la prima cosa che ti viene',
  },
  {
    id: 'D63', n: 63, section: 3,
    text: '"Merito di avere..."',
    type: 'FRASE',
    placeholder: 'Completa con la prima cosa che ti viene',
  },
  {
    id: 'D64', n: 64, section: 3,
    text: '"Essere vulnerabile significa..."',
    type: 'FRASE',
    placeholder: 'Completa con la prima cosa che ti viene',
  },
  {
    id: 'D65', n: 65, section: 3,
    text: '"Chiedere aiuto è..."',
    type: 'FRASE',
    placeholder: 'Completa con la prima cosa che ti viene',
  },
  {
    id: 'D66', n: 66, section: 3,
    text: '"Se fallisco, significa che..."',
    type: 'FRASE',
    placeholder: 'Completa con la prima cosa che ti viene',
  },
  {
    id: 'D67', n: 67, section: 3,
    text: '"Le persone di successo sono..."',
    type: 'FRASE',
    placeholder: 'Completa con la prima cosa che ti viene',
  },
  {
    id: 'D68', n: 68, section: 3,
    text: '"Per essere amato devo..."',
    type: 'FRASE',
    placeholder: 'Completa con la prima cosa che ti viene',
  },
  {
    id: 'D69', n: 69, section: 3,
    text: '"Prendermi cura di me è..."',
    type: 'FRASE',
    placeholder: 'Completa con la prima cosa che ti viene',
  },
  {
    id: 'D70', n: 70, section: 3,
    text: '"Non importa quanto mi impegni, non sarà mai abbastanza"',
    type: 'ACCORDO',
    subtext: '1 = Per niente — so riconoscere quando ho fatto abbastanza | 5 = Completamente — è una voce costante',
  },
  {
    id: 'D71', n: 71, section: 3,
    text: '"Il mio valore dipende da ciò che produco o realizzo"',
    type: 'ACCORDO',
    subtext: '1 = Per niente — il mio valore è indipendente dai risultati | 5 = Completamente',
  },
  {
    id: 'D72', n: 72, section: 3,
    text: '"Non posso permettermi di rallentare — se mi fermo perdo terreno"',
    type: 'ACCORDO',
    subtext: '1 = Per niente — so fermarmi e ricaricarmi | 5 = Completamente — fermarsi mi spaventa',
  },
  {
    id: 'D73', n: 73, section: 3,
    text: '"In fondo, non mi fido completamente delle persone"',
    type: 'ACCORDO',
    subtext: '1 = Per niente — mi fido con discernimento | 5 = Completamente — la fiducia è rara per me',
  },
  {
    id: 'D74', n: 74, section: 3,
    text: '"Ho una visione o una missione che pochi capiscono davvero"',
    type: 'ACCORDO',
    subtext: '1 = Per niente — comunico la mia visione e viene capita | 5 = Completamente — mi sento incompreso',
  },
  {
    id: 'D75', n: 75, section: 3,
    text: '"Devo fare tutto da solo per farlo bene"',
    type: 'ACCORDO',
    subtext: '1 = Per niente — so collaborare e fidarmi | 5 = Completamente — è più sicuro fare da soli',
  },
  {
    id: 'D76', n: 76, section: 3,
    text: '"Ho paura che se cambio troppo perderò qualcosa di essenziale"',
    type: 'ACCORDO',
    subtext: '1 = Per niente — il cambiamento non mi spaventa | 5 = Completamente — temo di perdere qualcosa',
  },
  {
    id: 'D77', n: 77, section: 3,
    text: '"I miei bisogni sono meno importanti di quelli degli altri"',
    type: 'ACCORDO',
    subtext: '1 = Per niente — i miei bisogni hanno lo stesso valore | 5 = Completamente — metto sempre gli altri prima',
  },
  {
    id: 'D78', n: 78, section: 3,
    text: '"Il denaro che guadagno difficilmente rimane — tende a sparire"',
    type: 'ACCORDO',
    subtext: '1 = Per niente — gestisco il denaro con stabilità | 5 = Completamente — è un pattern chiaro',
  },
  {
    id: 'D79', n: 79, section: 3,
    text: '"Se mostro chi sono davvero, le persone si allontaneranno"',
    type: 'ACCORDO',
    subtext: '1 = Per niente — essere autentico mi avvicina alle persone giuste | 5 = Completamente — mostrarmi è pericoloso',
  },
  {
    id: 'D80', n: 80, section: 3,
    text: '"Avere successo mi allontanerebbe dalle mie radici o da chi amo"',
    type: 'ACCORDO',
    subtext: '1 = Per niente — il mio successo non cambia le mie radici | 5 = Completamente — sento questa tensione',
  },
  {
    id: 'D81', n: 81, section: 3,
    text: 'La cosa di cui mi vergogno di più è...',
    type: 'FRASE',
    placeholder: 'Completa con la prima cosa che ti viene',
  },
  {
    id: 'D82', n: 82, section: 3,
    text: 'Non mi permetto di volere...',
    type: 'FRASE',
    placeholder: 'Completa con la prima cosa che ti viene',
  },
  {
    id: 'D83', n: 83, section: 3,
    text: 'La versione di me che ho paura di diventare è...',
    type: 'FRASE',
    placeholder: 'Completa con la prima cosa che ti viene',
  },
  {
    id: 'D84', n: 84, section: 3,
    text: 'Se potessi cambiare una credenza su me stesso, sarebbe...',
    type: 'FRASE',
    placeholder: 'Completa con la prima cosa che ti viene',
  },
];

// ─── SECTION 4 — LA STORIA E LE RADICI (D85–D104) ───────────────────────────

const SECTION_4_QUESTIONS: ScanQuestion[] = [
  {
    id: 'D85', n: 85, section: 4,
    text: 'Da bambino, come ti sentivi rispetto agli altri bambini?',
    type: 'SCELTA',
    options: [
      'Uguale agli altri — normale, incluso, a mio agio',
      'Diverso — più sensibile, più intenso, spesso non capito',
      'Responsabile — come se dovessi prendermi cura degli altri',
      'Invisibile — come se non contassi o non fossi visto',
      'Speciale — con qualcosa di unico che gli altri non avevano',
      'In competizione — dovevo sempre dimostrare il mio valore',
      'Non ho ricordi sufficientemente chiari di quell\'età',
    ],
  },
  {
    id: 'D86', n: 86, section: 4,
    text: 'Nella tua famiglia, come venivano gestite le emozioni?',
    type: 'SCELTA',
    options: [
      'Liberamente — si esprimevano, si ascoltavano, si elaboravano',
      'Si nascondevano — "non si fa vedere la debolezza"',
      'Con intensità — le emozioni dominavano tutto',
      'Si ignoravano — non se ne parlava mai',
      'Solo le emozioni positive erano accettate e visibili',
      'Non ho un\'immagine chiara di come funzionava in famiglia',
    ],
  },
  {
    id: 'D87', n: 87, section: 4,
    text: 'Com\'era il rapporto con l\'autorità nella tua famiglia?',
    type: 'SCELTA',
    options: [
      'Equilibrato — regole chiare ma rispetto reciproco',
      'Rigido — le regole erano legge, non si discuteva',
      'Caotico — non c\'erano confini o regole chiare',
      'Invertito — ero io ad avere responsabilità da adulto',
      'Oppressivo — mi sono sentito controllato o soffocato',
      'Non ho un\'immagine chiara del rapporto con l\'autorità in famiglia',
    ],
  },
  {
    id: 'D88', n: 88, section: 4,
    text: 'Qual era il messaggio implicito nella tua famiglia riguardo al denaro?',
    type: 'SCELTA',
    options: [
      'Sano — si guadagna con impegno, si gestisce con criterio',
      'Scarsità — i soldi non bastano mai, bisogna stare attenti',
      'Pericolo — i soldi corrompono o creano problemi',
      'Identità di classe — non siamo il tipo di persone che ha molti soldi',
      'Unica misura — il valore di una persona si misura dai soldi',
      'Tabù — di soldi non si parlava mai',
      'Non ho mai ricevuto messaggi chiari sul denaro',
    ],
  },
  {
    id: 'D89', n: 89, section: 4,
    text: 'Come veniva trattato il successo nella tua famiglia?',
    type: 'SCELTA',
    options: [
      'Celebrato e incoraggiato — il successo era motivo di gioia',
      'Relativizzato — "non esagerare", "non montarti la testa"',
      'Ignorato — non se ne parlava, non era rilevante',
      'Invidiato o criticato negli altri — il successo altrui era minaccia',
      'Fonte di pressione — dovevi sempre fare di più, non era mai abbastanza',
      'Non ho un ricordo chiaro di come veniva vissuto il successo',
    ],
  },
  {
    id: 'D90', n: 90, section: 4,
    text: 'C\'è stato un momento nella tua infanzia o adolescenza che ha cambiato il modo in cui ti vedi?',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
  {
    id: 'D91', n: 91, section: 4,
    text: 'Quali sono i messaggi che hai ricevuto su cosa significava essere "un uomo/una donna" nella tua famiglia o cultura?',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
  {
    id: 'D92', n: 92, section: 4,
    text: 'Hai mai sentito di dover essere diverso da quello che eri per essere accettato in famiglia?',
    type: 'ACCORDO',
    subtext: '1 = Per niente — potevo essere me stesso | 5 = Moltissimo — dovevo adattarmi costantemente',
  },
  {
    id: 'D93', n: 93, section: 4,
    text: 'Qualcuno nella tua famiglia ha avuto un rapporto difficile con il denaro o il successo che ti ha influenzato?',
    type: 'ACCORDO',
    subtext: '1 = Per niente — non vedo questa influenza in me | 5 = Moltissimo — sento chiaramente questa eredità',
  },
  {
    id: 'D94', n: 94, section: 4,
    text: 'Hai mai sentito il peso di aspettative non dette su chi dovevi diventare?',
    type: 'ACCORDO',
    subtext: '1 = Per niente — mi sono sentito libero di scegliere | 5 = Moltissimo — le aspettative pesavano',
  },
  {
    id: 'D95', n: 95, section: 4,
    text: 'C\'è qualcuno nella tua storia con cui non hai ancora fatto pace?',
    type: 'ACCORDO',
    subtext: '1 = No — ho elaborato le relazioni difficili del passato | 5 = Sì — porto ancora un peso irrisolto',
  },
  {
    id: 'D96', n: 96, section: 4,
    text: 'Qual è la cosa che hai giurato a te stesso di non diventare mai — e in quale area noti che ti ci stai avvicinando?',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
  {
    id: 'D97', n: 97, section: 4,
    text: 'Hai vissuto esperienze di perdita, tradimento, o abbandono che hanno cambiato il tuo modo di fidarti?',
    type: 'ACCORDO',
    subtext: '1 = No — mi fido con apertura e discernimento | 5 = Sì — quelle esperienze hanno cambiato il mio modo di fidarmi',
  },
  {
    id: 'D98', n: 98, section: 4,
    text: 'Come descriveresti il bambino che eri a 8-10 anni?',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
  {
    id: 'D99', n: 99, section: 4,
    text: 'Cosa ti direbbe il tuo io di 10 anni se potesse parlarti adesso?',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
  {
    id: 'D100', n: 100, section: 4,
    text: 'Quanto senti ancora oggi il peso delle aspettative della tua famiglia o cultura di origine?',
    type: 'SCALA',
    subtext: '1 = Per niente — sono libero da quel peso | 10 = Moltissimo — lo sento ogni giorno',
  },
  {
    id: 'D101', n: 101, section: 4,
    text: 'Hai mai fatto una scelta importante per non deludere qualcuno piuttosto che per te stesso?',
    type: 'ACCORDO',
    subtext: '1 = Mai — le mie scelte importanti vengono da me | 5 = Spesso — è un pattern che riconosco',
  },
  {
    id: 'D102', n: 102, section: 4,
    text: 'C\'è un sogno che hai abbandonato in passato per adattarti alle aspettative altrui?',
    type: 'ACCORDO',
    subtext: '1 = No — non ho abbandonato sogni per gli altri | 5 = Sì — c\'è qualcosa che ho lasciato andare',
  },
  {
    id: 'D103', n: 103, section: 4,
    text: 'Da bambino ho imparato che per essere amato dovevo...',
    type: 'FRASE',
    placeholder: 'Completa con la prima cosa che ti viene',
  },
  {
    id: 'D104', n: 104, section: 4,
    text: 'La paura più antica che porto dentro è...',
    type: 'FRASE',
    placeholder: 'Completa con la prima cosa che ti viene',
  },
];

// ─── SECTION 5 — I VALORI E LE PRIORITÀ (D105–D124) ─────────────────────────

const VALUES_OPTIONS = [
  'Libertà',
  'Sicurezza',
  'Amore e connessione',
  'Successo e realizzazione',
  'Contributo e impatto',
  'Salute e vitalità',
  'Crescita e evoluzione',
  'Piacere e divertimento',
];

const SECTION_5_QUESTIONS: ScanQuestion[] = [
  {
    id: 'D105', n: 105, section: 5,
    text: 'Ordina questi valori per come li vivi realmente — non come vorresti viverli:',
    type: 'RANK',
    options: VALUES_OPTIONS,
  },
  {
    id: 'D106', n: 106, section: 5,
    text: 'Quale di questi valori dici di avere ma fai più fatica a vivere concretamente?',
    type: 'SCELTA',
    options: VALUES_OPTIONS,
  },
  {
    id: 'D107', n: 107, section: 5,
    text: 'Per me il successo vero sarebbe...',
    type: 'FRASE',
    placeholder: 'Completa con la prima cosa che ti viene',
  },
  {
    id: 'D108', n: 108, section: 5,
    text: 'Quanto le tue giornate riflettono effettivamente ciò che conta di più per te?',
    type: 'SCALA',
    subtext: '1 = Per niente — vivo in contraddizione con i miei valori | 10 = Completamente allineato',
  },
  {
    id: 'D109', n: 109, section: 5,
    text: 'Se dovessi scegliere tra sicurezza e libertà, dove ti posizioneresti?',
    type: 'SCALA',
    subtext: '1 = Sicurezza totale | 10 = Libertà totale',
  },
  {
    id: 'D110', n: 110, section: 5,
    text: 'Quanto sei disposto a deludere gli altri pur di essere fedele a te stesso?',
    type: 'SCALA',
    subtext: '1 = Per niente — non riesco a deludere | 10 = Completamente — la mia autenticità viene prima',
  },
  {
    id: 'D111', n: 111, section: 5,
    text: 'Qual è la cosa per cui saresti disposto a rischiare tutto?',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
  {
    id: 'D112', n: 112, section: 5,
    text: 'Quanto senti che stai vivendo una vita che hai scelto vs una vita che è successa?',
    type: 'SCALA',
    subtext: '1 = Una vita che è successa — non mi sento protagonista | 10 = Una vita che ho scelto',
  },
  {
    id: 'D113', n: 113, section: 5,
    text: 'Se potessi cambiare una sola cosa della tua vita da domani, cosa cambieresti?',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
  {
    id: 'D114', n: 114, section: 5,
    text: 'Quanto spesso fai cose perché "si deve fare" piuttosto che perché le vuoi davvero?',
    type: 'SCALA',
    subtext: '1 = Quasi mai — agisco da scelta genuina | 10 = Quasi sempre — vivo di "si deve"',
  },
  {
    id: 'D115', n: 115, section: 5,
    text: 'Il mio tempo viene rubato principalmente da...',
    type: 'FRASE',
    placeholder: 'Completa con la prima cosa che ti viene',
  },
  {
    id: 'D116', n: 116, section: 5,
    text: 'Quanto senti di stare vivendo in accordo con i tuoi valori più profondi?',
    type: 'SCALA',
    subtext: '1 = Per niente — c\'è un gap enorme | 10 = Completamente — vita e valori sono allineati',
  },
  {
    id: 'D117', n: 117, section: 5,
    text: 'Tra successo esterno e pace interiore, dove stai investendo più energia?',
    type: 'SCELTA',
    options: [
      'Prevalentemente successo esterno',
      'Prevalentemente pace interiore',
      'Cerco di bilanciare i due',
      'Nessuno dei due — sono in modalità sopravvivenza',
    ],
  },
  {
    id: 'D118', n: 118, section: 5,
    text: 'Sarei disposto a sacrificare qualsiasi cosa pur di...',
    type: 'FRASE',
    placeholder: 'Completa con la prima cosa che ti viene',
  },
  {
    id: 'D119', n: 119, section: 5,
    text: '"Sto vivendo la vita che voglio, non quella che gli altri si aspettano da me"',
    type: 'ACCORDO',
    subtext: '1 = Per niente — vivo per le aspettative altrui | 5 = Completamente — questa è la mia vita',
  },
  {
    id: 'D120', n: 120, section: 5,
    text: 'Cosa ti fa sentire vivo — completamente presente e pieno?',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
  {
    id: 'D121', n: 121, section: 5,
    text: 'Cosa ti svuota — ti lascia esausto o disconnesso da te stesso?',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
  {
    id: 'D122', n: 122, section: 5,
    text: 'La persona che ammiro di più è _____ perché...',
    type: 'FRASE',
    placeholder: 'Completa con la prima cosa che ti viene',
  },
  {
    id: 'D123', n: 123, section: 5,
    text: 'Quanto senti di stare esprimendo il tuo pieno potenziale?',
    type: 'SCALA',
    subtext: '1 = Per niente — sento un divario enorme | 10 = Completamente — sono in piena espressione',
  },
  {
    id: 'D124', n: 124, section: 5,
    text: 'Se sapessi che non puoi fallire, costruirei...',
    type: 'FRASE',
    placeholder: 'Completa con la prima cosa che ti viene',
  },
];

// ─── SECTION 6 — L'IDENTITÀ TARGET (D125–D139) ───────────────────────────────

const SECTION_6_QUESTIONS: ScanQuestion[] = [
  {
    id: 'D125', n: 125, section: 6,
    text: 'Descrivi la versione più evoluta di te — tra 5 anni — in modo specifico e concreto.',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
  {
    id: 'D126', n: 126, section: 6,
    text: 'Quella versione di te — come si comporta in una situazione di stress?',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
  {
    id: 'D127', n: 127, section: 6,
    text: 'Quella versione di te — come gestisce il denaro?',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
  {
    id: 'D128', n: 128, section: 6,
    text: 'Quella versione di te — come si prende cura di sé?',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
  {
    id: 'D129', n: 129, section: 6,
    text: 'Quella versione di te — come vive le relazioni?',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
  {
    id: 'D130', n: 130, section: 6,
    text: 'Quella versione di te — cosa pensa di te attuale?',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
  {
    id: 'D131', n: 131, section: 6,
    text: 'Cosa deve essere vero su di te — a livello di identità — per essere già quella persona?',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
  {
    id: 'D132', n: 132, section: 6,
    text: 'Qual è la credenza che quella versione di te ha su se stesso che tu non hai ancora?',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
  {
    id: 'D133', n: 133, section: 6,
    text: 'Come si chiama quella versione di te? Dagli un nome o un titolo.',
    type: 'FRASE',
    placeholder: 'Un nome, un titolo, una parola che la rappresenti',
  },
  {
    id: 'D134', n: 134, section: 6,
    text: 'Cosa sta aspettando quella versione di te che tu inizi a fare?',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
  {
    id: 'D135', n: 135, section: 6,
    text: 'Cosa dovrebbe smettere di fare la versione attuale di te?',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
  {
    id: 'D136', n: 136, section: 6,
    text: 'In quale area vuoi evolvere prioritariamente?',
    type: 'SCELTA',
    options: [
      'Salute & Corpo',
      'Relazioni & Amore',
      'Famiglia',
      'Business & Carriera',
      'Finanze & Abbondanza',
      'Crescita Personale',
      'Divertimento & Creatività',
      'Contributo & Scopo',
    ],
  },
  {
    id: 'D137', n: 137, section: 6,
    text: 'Su una scala, dove sei oggi rispetto alla versione di te che vuoi essere?',
    type: 'SCALA',
    subtext: '1 = Molto lontano | 10 = Sono già quella persona',
  },
  {
    id: 'D138', n: 138, section: 6,
    text: 'Cosa ti ha impedito finora di essere già quella persona?',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
  {
    id: 'D139', n: 139, section: 6,
    text: 'Sei pronto a fare quello che serve — anche quando sarà scomodo?',
    type: 'SCALA',
    subtext: '1 = Non ancora — ho bisogno di più chiarezza | 10 = Completamente — sono pronto adesso',
  },
];

// ─── SECTION 7 — LO STATO ATTUALE (D140–D150) ────────────────────────────────

const SECTION_7_QUESTIONS: ScanQuestion[] = [
  {
    id: 'D140', n: 140, section: 7,
    text: 'Come stai in questo momento?',
    type: 'SCALA',
    subtext: '1 = Male — sono in un periodo difficile | 10 = Bene — sono in uno stato ottimale',
  },
  {
    id: 'D141', n: 141, section: 7,
    text: 'Qual è la cosa che ti pesa di più in questo periodo?',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
  {
    id: 'D142', n: 142, section: 7,
    text: 'Qual è la cosa che ti dà più energia in questo periodo?',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
  {
    id: 'D143', n: 143, section: 7,
    text: 'Quanto senti di avere chiarezza su dove stai andando?',
    type: 'SCALA',
    subtext: '1 = Per niente — sono confuso | 10 = Completamente — ho una direzione chiara',
  },
  {
    id: 'D144', n: 144, section: 7,
    text: 'Quanto senti di avere il controllo sulla tua vita in questo momento?',
    type: 'SCALA',
    subtext: '1 = Per niente — mi sento trascinato dagli eventi | 10 = Completamente — sono io al timone',
  },
  {
    id: 'D145', n: 145, section: 7,
    text: 'C\'è qualcosa di importante che stai evitando in questo periodo?',
    type: 'ACCORDO',
    subtext: '1 = No — afffronto ciò che si presenta | 5 = Sì — lo so e continuo ad evitarlo',
  },
  {
    id: 'D146', n: 146, section: 7,
    text: 'Qual è la decisione più importante che devi prendere adesso e che stai rimandando?',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
  {
    id: 'D147', n: 147, section: 7,
    text: 'Quanto sei soddisfatto di come stai usando il tuo tempo e la tua energia?',
    type: 'SCALA',
    subtext: '1 = Per niente — spreco tempo e energie | 10 = Completamente — uso tutto con intenzione',
  },
  {
    id: 'D148', n: 148, section: 7,
    text: 'In questo momento, stai operando più da paura o da visione?',
    type: 'SCALA',
    subtext: '1 = Paura totale | 10 = Visione totale',
  },
  {
    id: 'D149', n: 149, section: 7,
    text: 'Cosa ti aspetti da SELF OS? Cosa vorresti che cambiasse nella tua vita?',
    type: 'TESTO',
    placeholder: 'Scrivi qui liberamente...',
  },
  {
    id: 'D150', n: 150, section: 7,
    text: 'C\'è qualcosa di importante su di te che non ti abbiamo chiesto?',
    type: 'TESTO',
    placeholder: 'Spazio aperto — scrivi ciò che senti importante condividere',
  },
];

// ─── Exported data ─────────────────────────────────────────────────────────────

export const SCAN_SECTIONS: ScanSection[] = [
  {
    n: 1,
    title: 'La Ruota della Vita',
    subtitle: 'Partiamo da dove sei adesso',
    questions: SECTION_1_QUESTIONS,
  },
  {
    n: 2,
    title: 'I Pattern Comportamentali',
    subtitle: 'Come ti comporti davvero',
    questions: SECTION_2_QUESTIONS,
  },
  {
    n: 3,
    title: 'Le Credenze Fondanti',
    subtitle: 'Le storie invisibili che governano tutto',
    questions: SECTION_3_QUESTIONS,
  },
  {
    n: 4,
    title: 'La Storia e le Radici',
    subtitle: 'Da dove vengono i tuoi pattern',
    questions: SECTION_4_QUESTIONS,
  },
  {
    n: 5,
    title: 'I Valori e le Priorità',
    subtitle: 'Cosa conta davvero',
    questions: SECTION_5_QUESTIONS,
  },
  {
    n: 6,
    title: "L'Identità Target",
    subtitle: 'Chi stai diventando',
    questions: SECTION_6_QUESTIONS,
  },
  {
    n: 7,
    title: 'Lo Stato Attuale',
    subtitle: 'Dove sei adesso',
    questions: SECTION_7_QUESTIONS,
  },
];

export const ALL_QUESTIONS: ScanQuestion[] = SCAN_SECTIONS.flatMap(s => s.questions);

export function getQuestion(id: string): ScanQuestion | undefined {
  return ALL_QUESTIONS.find(q => q.id === id);
}

export function getSectionQuestions(section: number): ScanQuestion[] {
  return ALL_QUESTIONS.filter(q => q.section === section);
}
